[package]
name = "stacc"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
lto = "off"

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"

[dependencies]
logos = "0.12"